set(headers ${headers}
	Testing/DeathDistributionTests.h
	Testing/DistributionTests.h
	Testing/OutfitManagerTests.h
	Testing/Testing.h
	Testing/TestsHelpers.h
	include/Cache.h
	include/DeathDistribution.h
	include/Defs.h
	include/DependencyResolver.h
	include/Distribute.h
	include/DistributeManager.h
	include/DistributePCLevelMult.h
	include/ExclusiveGroups.h
	include/FormData.h
	include/Hooking.h
	include/KeywordDependencies.h
	include/LinkedDistribution.h
	include/LogBuffer.h
	include/LogHeader.h
	include/LookupConfigs.h
	include/LookupFilters.h
	include/LookupForms.h
	include/LookupNPC.h
	include/OutfitManager.h
	include/PCH.h
	include/PCLevelMultManager.h
	include/Parser.h
)
