set(headers ${headers}
	include/Cache.h
	include/Defs.h
	include/DependencyResolver.h
	include/Distribute.h
	include/DistributeManager.h
	include/DistributePCLevelMult.h
	include/ExclusiveGroups.h
	include/FormData.h
	include/KeywordDependencies.h
	include/LinkedDistribution.h
	include/LogBuffer.h
	include/LookupConfigs.h
	include/LookupFilters.h
	include/LookupForms.h
	include/LookupNPC.h
	include/PCH.h
	include/PCLevelMultManager.h
)
