name: Main

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
    - '[0-9]+.[0-9]+.[0-9]+.rc[0-9]+'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  run:
    if: github.repository_owner == 'powerof3'
    uses: adya/pack-skse-mod/.github/workflows/pack.yml@ng
    with:
      CMAKE_LISTS_PATH: 'SPID/CMakeLists.txt'
      VCPKG_JSON_PATH: 'SPID/vcpkg.json'
      CMAKE_PROJECT_DIR: 'SPID'
      MOD_NAME: "Spell Perk Item Distributor"
