name: Main

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
    - '[0-9]+.[0-9]+.[0-9]+.rc[0-9]+'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    if: github.repository_owner == 'powerof3'
    uses: adya/pack-skse-mod/.github/workflows/pack.yml@main
    with:
      CMAKE_PROJECT_DIR: "SPID"
      CMAKE_VR_CONFIG_PRESET: ''
      CMAKE_VR_BUILD_PRESET: ''
      FOMOD_INCLUDE_PDB: true
      FOMOD_MOD_NAME: "Spell Perk Item Distributor"
      FOMOD_MOD_AUTHOR: "powerofthree"
      FOMOD_MOD_NEXUS_ID: "36869"
      FOMOD_SE_MIN_GAME_VERSION: '1.5'
      FOMOD_AE_MIN_GAME_VERSION: '1.6'
      FOMOD_DEFAULT_IMAGE: "FOMOD/images/cover.png"
      PUBLISH_MOD_CHANGELOG_FILE: "FOMOD/changelog.txt"
      PUBLISH_MOD_DESCRIPTION_FILE: "FOMOD/description.txt"
      PUBLISH_ARCHIVE_TYPE: '7z'
      VCPKG_COMMIT_ID: 'b545373a9a536dc559dac8583467a21497a0e897'
