name: Main

on:
  push:
    tags:
    - '[0-9]+.[0-9]+.[0-9]+'
    - '[0-9]+.[0-9]+.[0-9]+.rc[0-9]+'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.repository_owner == 'powerof3'
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgJsonGlob: 'vcpkg.json'

    - name: Configure
      shell: pwsh
      run: cmake --preset vs2026-windows-vcpkg

    - name: Build
      shell: pwsh
      run: cmake --build --preset vs2026-windows-vcpkg

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: po3_SpellPerkItemDistributor-${{ github.ref_name }}
        if-no-files-found: error
        path: |
          build/SPID/Release/po3_SpellPerkItemDistributor.dll
          build/SPID/Release/po3_SpellPerkItemDistributor.pdb
