name: Main

on:
  push:
    branches: '**'
    tags: '*'

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  run:
    if: github.repository_owner == 'powerof3'
    uses: adya/pack-skse-mod/.github/workflows/pack.yml@main
    with:
      CMAKE_PROJECT_DIR: "SPID"
      CMAKE_VR_CONFIG_PRESET: ''
      CMAKE_VR_BUILD_PRESET: ''
      AE_353_BRANCH: fixes/6.1.0-ae353
      FOMOD_INCLUDE_PDB: true
      FOMOD_MOD_NAME: "Spell Perk Item Distributor"
      FOMOD_MOD_AUTHOR: "powerofthree"
      FOMOD_MOD_NEXUS_ID: "36869"
      FOMOD_DEFAULT_IMAGE: "FOMOD/images/cover.png"
      PUBLISH_MOD_CHANGELOG_FILE: "FOMOD/changelog.txt"
      PUBLISH_MOD_DESCRIPTION_FILE: "FOMOD/description.txt"
      PUBLISH_ARCHIVE_TYPE: '7z'
